version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/hello-node

permissions:
- object: /home/ubuntu/hello-node/
  pattern: "**"
  mode: 777
  owner: ubuntu
  group: ubuntu
  type:
    - directory
    - file


hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 600
      runas: ubuntu
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 100
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ubuntu